import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientProvider from "../../providers/client-providers";
import { MapProvider } from "../../providers/map-providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Velosure",
  description: "Generated by @osdk/create-app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body className={inter.className}>
        <ClientProvider>
          <MapProvider>
            {children}
          </MapProvider>
        </ClientProvider>
      </body>
    </html>
  );
}

export default RootLayout;